# ============================================================
# MediReport AI — PDF Generation Service (REWRITTEN)
# File: backend/services/pdf_service.py
#
# Generates professional lab report PDFs using ReportLab.
# Key improvements:
#   - Uses centralized Supabase client
#   - Safe character handling for Unicode/Urdu text
#   - Detailed error logging
#   - Graceful degradation on font issues
#   - Background task success/failure logging
#
# PDF Sections:
#   1. Header    — Hospital logo + name (or MediReport AI branding)
#   2. Patient   — Info + report date + report ID
#   3. Urdu      — RTL explanation text (best-effort)
#   4. English   — LTR explanation text
#   5. Abnormals — Color-coded table (RED=HIGH, ORANGE=LOW, GREEN=normal)
#   6. Footer    — "Generated by MediReport AI"
# ============================================================

import io
import logging
import re
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from config.settings import settings
from config.supabase_client import get_supabase_client, safe_storage_upload

logger = logging.getLogger("medireport.pdf")


# ── Color Palette ─────────────────────────────────────────
COLOR_PRIMARY      = colors.HexColor("#0ea5e9")   # MediReport AI blue
COLOR_DARK         = colors.HexColor("#0f172a")   # Dark slate
COLOR_DANGER       = colors.HexColor("#ef4444")   # RED — HIGH / CRITICAL_HIGH
COLOR_WARNING      = colors.HexColor("#f97316")   # ORANGE — LOW
COLOR_CRITICAL     = colors.HexColor("#dc2626")   # DARK RED — CRITICAL
COLOR_SUCCESS      = colors.HexColor("#22c55e")   # GREEN — normal
COLOR_LIGHT_BG     = colors.HexColor("#f8fafc")   # Section background
COLOR_BORDER       = colors.HexColor("#e2e8f0")   # Table border
COLOR_URDU_BG      = colors.HexColor("#fdf4ff")   # Subtle purple for Urdu section
COLOR_WHITE        = colors.white


# ── Font Handling ─────────────────────────────────────────
def _safe_text(text: str | None, max_len: int = 5000) -> str:
    """
    Clean text for PDF generation.
    
    - Removes control characters
    - Truncates if too long
    - Handles None
    - Escapes XML-like entities
    
    Args:
        text: Input text
        max_len: Maximum length
        
    Returns:
        Safe text for PDF
    """
    if not text:
        return ""
    
    # Remove control characters (keep newlines)
    text = "".join(c for c in text if c == "\n" or ord(c) >= 32)
    
    # Escape XML special chars for ReportLab
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # Normalize newlines
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    
    # Truncate
    if len(text) > max_len:
        text = text[: max_len - 3] + "..."
    
    return text


def _has_arabic_script(text: str) -> bool:
    """Check if text contains Arabic/Urdu script characters."""
    if not text:
        return False
    # Arabic script Unicode range: \u0600-\u06FF
    return bool(re.search(r"[\u0600-\u06FF]", text))


# ── Style Builders ────────────────────────────────────────

def _build_styles() -> dict[str, ParagraphStyle]:
    """Build all PDF paragraph styles."""
    base = getSampleStyleSheet()

    return {
        "hospital_name": ParagraphStyle(
            "HospitalName",
            fontSize=20,
            fontName="Helvetica-Bold",
            textColor=COLOR_WHITE,
            alignment=TA_CENTER,
            leading=24,
        ),
        "tagline": ParagraphStyle(
            "Tagline",
            fontSize=10,
            fontName="Helvetica",
            textColor=colors.HexColor("#cbd5e1"),
            alignment=TA_CENTER,
        ),
        "section_title": ParagraphStyle(
            "SectionTitle",
            fontSize=13,
            fontName="Helvetica-Bold",
            textColor=COLOR_DARK,
            spaceBefore=6,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "Body",
            fontSize=10,
            fontName="Helvetica",
            textColor=COLOR_DARK,
            leading=14,
            spaceAfter=6,
        ),
        "body_bold": ParagraphStyle(
            "BodyBold",
            fontSize=10,
            fontName="Helvetica-Bold",
            textColor=COLOR_DARK,
            leading=14,
        ),
        "urdu_section": ParagraphStyle(
            "UrduSection",
            fontSize=11,
            fontName="Helvetica",
            textColor=COLOR_DARK,
            leading=16,
            alignment=TA_RIGHT,
            rightIndent=0,
        ),
        "abnormal_red": ParagraphStyle(
            "AbnormalRed",
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=COLOR_DANGER,
        ),
        "abnormal_orange": ParagraphStyle(
            "AbnormalOrange",
            fontSize=9,
            fontName="Helvetica-Bold",
            textColor=COLOR_WARNING,
        ),
        "abnormal_green": ParagraphStyle(
            "AbnormalGreen",
            fontSize=9,
            fontName="Helvetica",
            textColor=COLOR_SUCCESS,
        ),
        "footer": ParagraphStyle(
            "Footer",
            fontSize=8,
            fontName="Helvetica",
            textColor=colors.HexColor("#64748b"),
            leading=10,
        ),
        "disclaimer": ParagraphStyle(
            "Disclaimer",
            fontSize=8,
            fontName="Helvetica-Oblique",
            textColor=colors.HexColor("#94a3b8"),
            leading=10,
        ),
    }


# ── PDF Builder ───────────────────────────────────────────

def _build_pdf_bytes(
    report_id: str,
    explanation_en: str,
    explanation_ur: str,
    abnormal_values: list[dict],
    hospital: Optional[dict] = None,
    patient_name: Optional[str] = None,
    created_at: Optional[str] = None,
) -> bytes:
    """
    Build PDF bytes using ReportLab.
    
    Args:
        report_id: UUID of the report
        explanation_en: English explanation
        explanation_ur: Urdu explanation (may contain Arabic script)
        abnormal_values: List of abnormal value dicts
        hospital: Optional hospital branding dict
        patient_name: Optional patient name
        created_at: Optional ISO timestamp
        
    Returns:
        PDF as bytes
        
    Raises:
        RuntimeError: If PDF generation fails
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = _build_styles()
    story: list = []

    # ── SECTION 1: Header ───────────────────────────────
    hospital_name = hospital.get("name", "MediReport AI") if hospital else "MediReport AI"
    tagline = hospital.get("tagline", "AI-Powered Lab Report Analysis") if hospital else "AI-Powered Lab Report Analysis"
    
    header_bg = hospital.get("primary_color", "#0ea5e9") if hospital else "#0ea5e9"
    try:
        header_color = colors.HexColor(header_bg)
    except:
        header_color = COLOR_PRIMARY

    # Header box (colored background)
    header_data = [[
        Paragraph(
            f"<font size=22><b>{_safe_text(hospital_name, 100)}</b></font>",
            ParagraphStyle(
                "HeaderHospital",
                fontSize=22,
                fontName="Helvetica-Bold",
                textColor=COLOR_WHITE,
                alignment=TA_CENTER,
            ),
        ),
    ], [
        Paragraph(
            _safe_text(tagline, 200),
            ParagraphStyle(
                "HeaderTagline",
                fontSize=10,
                fontName="Helvetica",
                textColor=colors.HexColor("#e2e8f0"),
                alignment=TA_CENTER,
            ),
        ),
    ]]
    
    header_table = Table(header_data, colWidths=[170 * mm])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), header_color),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("BOX", (0, 0), (-1, -1), 0.5, header_color),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 4 * mm))

    # ── SECTION 2: Patient Info ───────────────────────
    date_str = "Unknown Date"
    if created_at:
        try:
            dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            date_str = dt.strftime("%B %d, %Y at %I:%M %p")
        except:
            date_str = str(created_at)[:19]

    patient = _safe_text(patient_name, 100) if patient_name else "Anonymous Patient"
    rid = report_id[:8] if len(report_id) >= 8 else report_id

    info_data = [
        [Paragraph("<b>Patient:</b> " + patient, styles["body_bold"]),
         Paragraph("<b>Report Date:</b> " + date_str, styles["body"])],
        [Paragraph("<b>Report ID:</b> " + rid, styles["body"]), ""],
    ]
    info_table = Table(info_data, colWidths=[85 * mm, 85 * mm])
    info_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 4 * mm))

    # ── SECTION 3: Urdu Explanation (RTL) ─────────────
    if explanation_ur:
        story.append(Paragraph("<b>Urdu Explanation</b>", styles["section_title"]))
        
        # Note about RTL fonts
        urdu_content = _safe_text(explanation_ur, 2500)
        if _has_arabic_script(urdu_content):
            urdu_content += "\n\n<i>(Note: For best Urdu rendering, please use the web app or request an Urdu-specific PDF)</i>"
        
        urdu_para = Paragraph(urdu_content.replace("\n", "<br/>"), styles["urdu_section"])
        
        urdu_box = Table([[urdu_para]], colWidths=[170 * mm])
        urdu_box.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_URDU_BG),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
        ]))
        story.append(urdu_box)
        story.append(Spacer(1, 4 * mm))

    # ── SECTION 4: English Explanation ────────────────
    story.append(Paragraph("<b>English Explanation</b>", styles["section_title"]))
    en_content = _safe_text(explanation_en, 2500) or "No explanation available."
    en_para = Paragraph(en_content.replace("\n", "<br/>"), styles["body"])
    
    en_box = Table([[en_para]], colWidths=[170 * mm])
    en_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), COLOR_LIGHT_BG),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
    ]))
    story.append(en_box)
    story.append(Spacer(1, 6 * mm))

    # ── SECTION 5: Abnormal Values Table ──────────────
    if abnormal_values:
        story.append(Paragraph("<b>Abnormal Values Detected</b>", styles["section_title"]))
        
        # Header row
        table_data = [[
            Paragraph("<b>Test</b>", styles["body_bold"]),
            Paragraph("<b>Your Value</b>", styles["body_bold"]),
            Paragraph("<b>Unit</b>", styles["body_bold"]),
            Paragraph("<b>Normal Range</b>", styles["body_bold"]),
            Paragraph("<b>Status</b>", styles["body_bold"]),
        ]]
        
        for val in abnormal_values[:20]:  # Limit to first 20
            status = (val.get("status") or "UNKNOWN").upper()
            name = _safe_text(val.get("name", "Unknown"), 50)
            value = _safe_text(val.get("value", "-"), 20)
            unit = _safe_text(val.get("unit", ""), 15)
            nrange = _safe_text(val.get("normal_range", ""), 20)
            
            if status in ("HIGH", "CRITICAL_HIGH"):
                status_style = "abnormal_red"
                status_text = "🔴 HIGH"
            elif status in ("LOW", "CRITICAL_LOW"):
                status_style = "abnormal_orange"
                status_text = "🟠 LOW"
            else:
                status_style = "abnormal_green"
                status_text = "🟢 " + status
            
            table_data.append([
                Paragraph(name, styles["body"]),
                Paragraph(value, styles[status_style]),
                Paragraph(unit, styles["body"]),
                Paragraph(nrange, styles["body"]),
                Paragraph(status_text, styles[status_style]),
            ])
        
        abnormal_table = Table(
            table_data,
            colWidths=[45 * mm, 30 * mm, 25 * mm, 35 * mm, 35 * mm],
        )
        abnormal_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), COLOR_WHITE),
            ("ALIGN", (0, 0), (-1, 0), "CENTER"),
            ("ALIGN", (1, 1), (-1, -1), "CENTER"),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 10),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
            ("BACKGROUND", (0, 1), (-1, -1), COLOR_LIGHT_BG),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 1), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ]))
        story.append(abnormal_table)
        story.append(Spacer(1, 4 * mm))
    
    # Legend
    legend_data = [[
        Paragraph("<font color='#ef4444'>●</font> High/Above Normal", styles["body"]),
        Paragraph("<font color='#f97316'>●</font> Low/Below Normal", styles["body"]),
        Paragraph("<font color='#22c55e'>●</font> Within Normal", styles["body"]),
    ]]
    legend_table = Table(legend_data, colWidths=[56 * mm, 56 * mm, 56 * mm])
    legend_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
    ]))
    story.append(legend_table)
    story.append(Spacer(1, 0.8 * cm))

    # ── SECTION 6: Footer ──────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=COLOR_BORDER, spaceAfter=6))
    story.append(Paragraph(
        f"Generated by <b>MediReport AI</b> | medireport.ai | "
        f"Report ID: {rid} | {date_str} | "
        f"<i>This report is AI-generated and does not replace professional medical advice.</i>",
        styles["footer"],
    ))

    # Build PDF
    doc.build(story)
    buf.seek(0)
    return buf.read()


# ── Public API ───────────────────────────────────────────

async def generate_report_pdf(
    report_id: str,
    user_id: str,
    explanation_en: str,
    explanation_ur: str,
    abnormal_values: list[dict],
    patient_name: Optional[str] = None,
    created_at: Optional[str] = None,
    hospital_id: Optional[str] = None,
) -> dict[str, any]:
    """
    Generate a professional PDF for a lab report and upload to Supabase Storage.
    
    Args:
        report_id: UUID of the report.
        user_id: UUID of the report owner.
        explanation_en: English explanation from NLP service.
        explanation_ur: Urdu translation.
        abnormal_values: List of {name, value, unit, normal_range, status} dicts.
        patient_name: Optional patient display name.
        created_at: Report creation timestamp (ISO string).
        hospital_id: Optional hospital UUID for white-label branding.
        
    Returns:
        Dict with:
        - pdf_url: Public URL of the generated PDF
        - success: Boolean success status
        - bytes_generated: Size of PDF in bytes
        - error: Error message if failed
        
    Raises:
        ValueError: If required parameters missing.
        RuntimeError: If PDF generation or upload fails.
    """
    if not report_id or not user_id:
        raise ValueError("report_id and user_id are required to generate PDF.")
    
    logger.info("PDF generation started | report=%s hospital=%s", report_id, hospital_id)
    
    try:
        # Fetch hospital branding if available
        hospital: Optional[dict] = None
        if hospital_id:
            try:
                supabase = get_supabase_client()
                h_result = (
                    supabase.table("hospitals")
                    .select("name, logo_url, primary_color")
                    .eq("id", hospital_id)
                    .single()
                    .execute()
                )
                hospital = h_result.data
                logger.info("Hospital branding fetched | hospital=%s", hospital_id)
            except Exception as exc:
                logger.warning("Could not fetch hospital branding: %s", exc)
        
        # Normalize abnormals
        safe_abnormals = [a for a in (abnormal_values or []) if isinstance(a, dict)]
        
        # Build PDF bytes
        try:
            pdf_bytes = _build_pdf_bytes(
                report_id=report_id,
                explanation_en=explanation_en or "",
                explanation_ur=explanation_ur or "",
                abnormal_values=safe_abnormals,
                hospital=hospital,
                patient_name=patient_name,
                created_at=created_at,
            )
            pdf_size = len(pdf_bytes)
            logger.info("PDF built | report=%s size=%d bytes", report_id, pdf_size)
        except Exception as exc:
            logger.error("PDF build failed | report=%s error=%s", report_id, exc, exc_info=True)
            raise RuntimeError(f"PDF generation failed: {exc}") from exc
        
        # Upload to Supabase Storage
        storage_path = f"{user_id}/{report_id}/report.pdf"
        try:
            pdf_url = await safe_storage_upload(
                bucket=settings.pdfs_bucket,
                path=storage_path,
                file_data=pdf_bytes,
                content_type="application/pdf",
            )
            logger.info("PDF uploaded | report=%s path=%s", report_id, storage_path)
        except Exception as exc:
            logger.error("PDF upload failed | report=%s error=%s", report_id, exc, exc_info=True)
            raise RuntimeError(f"PDF upload failed: {exc}") from exc
        
        # Update report record with pdf_url
        try:
            supabase = get_supabase_client()
            supabase.table("reports").update({"pdf_url": pdf_url}).eq("id", report_id).execute()
            logger.info("PDF URL saved to DB | report=%s", report_id)
        except Exception as exc:
            logger.warning("Could not save pdf_url to DB | report=%s error=%s", report_id, exc)
        
        logger.info("PDF generation complete | report=%s pdf_url=%s", report_id, pdf_url)
        
        return {
            "success": True,
            "pdf_url": pdf_url,
            "bytes_generated": pdf_size,
            "error": None,
        }
        
    except Exception as exc:
        logger.error(
            "PDF generation failed | report=%s error=%s",
            report_id, exc, exc_info=True,
        )
        return {
            "success": False,
            "pdf_url": None,
            "bytes_generated": 0,
            "error": str(exc),
        }


__all__ = ["generate_report_pdf"]
